# action.yml
name: "Algorithmia - Multiple Algorithm Caller"
description: "Call multiple algorithms on Algorithmia in parallel and collect the results"
branding:
  icon: "alert-circle"
  color: "yellow"
inputs:
  api_key:
    description: "Algorithmia API key"
    required: true
  parallel_algo_names:
    description: "Algorithm names to call in parallel, as a list of strings"
    required: true
  parallel_algo_input:
    description: "Algorithm input to for multiple execution, as a list of strings"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.api_key }}
    - ${{ inputs.parallel_algo_names }}
    - ${{ inputs.parallel_algo_input }}